sudo: required
services:
  - docker

before_install:
  - docker build -t test-image -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true test-image npm run test -- --coverage

after_success:
  - docker build -t ckilcioglu/multi-client ./client
  - docker build -t ckilcioglu/multi-nginx ./nginx
  - docker build -t ckilcioglu/multi-server ./server
  - docker build -t ckilcioglu/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push ckilcioglu/multi-client
  - docker push ckilcioglu/multi-nginx
  - docker push ckilcioglu/multi-server
  - docker push ckilcioglu/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-766003108064"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
