version: '3'
services:
  nginx:
    image: "ckilcioglu/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
      - client  
  server:
    image: "ckilcioglu/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    mage: "ckilcioglu/multi-client"
    mem_limit: 128m
    hostname: client
  worker:
    mage: "ckilcioglu/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

